#Configuracion sERVIDOR
server.port: 8115
#Configuracion de Base de Datos
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/isacode"
spring.datasource.driver-class-name: "org.postgresql.Driver"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#Configuracion de Correo Electronico
spring.mail.debug: "false" 
spring.mail.smtp.port: 465
spring.mail.password: "D3GVAErIv);_"
spring.mail.smtp.user: "info@isacode.com"
spring.mail.transport.protocol: "smtp" 
spring.mail.smtp.debug: "false"
spring.mail.smtp.host: "gator3232.hostgator.com"
spring.mail.smtp.auth: "true"
spring.mail.smtp.ssl.enable: "true"
