#Configuracion sERVIDOR
server.port: 8115
#Configuracion de Base de Datos
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/isacode"
spring.datasource.driver-class-name: "org.postgresql.Driver"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#Configuracion de Correo Electronico
spring.mail.host: "gator4258.hostgator.com"
spring.mail.port: 465
spring.mail.username: "info@trisqel.com"
spring.mail.password: "VrrLufkqF3Qf"
spring.mail.properties.mail.smtp.starttls.enable: "true"
spring.mail.properties.mail.smtp.starttls.required: "true"
spring.mail.properties.mail.smtp.auth: "true"
spring.mail.properties.mail.smtp.connectiontimeout: 15000
spring.mail.properties.mail.smtp.timeout: 15000
spring.mail.properties.mail.smtp.writetimeout: 15000
spring.thymeleaf.check-template-location: false
